server:
  port: 2020
spring:
  application:
    name: sob-blog-system
  datasource:
    url: jdbc:mysql://localhost:3306/sob_blog_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password